### ISSUE TITLE
The obtained label file has one less line than the real scene.

### ISSUE THREAD

**Issue by zzusunquan** [loicland/superpoint_graph#173]
Hi 
while  i run 
`python partition/write_Semantic3d.py --SEMA3D_PATH $SEMA3D_DIR --odir "results/sema3d/trainval_best" --db_test_name testred`
The obtained label file has one less line than the real scene.
for example :
![image](https://user-images.githubusercontent.com/48703273/69245927-bd05a680-0be2-11ea-947e-0e989145da62.png)
![image](https://user-images.githubusercontent.com/48703273/69246016-e1fa1980-0be2-11ea-8e83-05c368193066.png)
Predicted MarketplaceFeldkirch_Station4.label file is 10538632 lines ,but the real scene it is 10538633   . the same problem happend in the other  .label file ,just  one less  line than the real scene .

**Comment by loicland** [comment]
Hi,

It is indeed a bug, it should be fixed now. Let me know if the latest commit fixes your issue.

**Comment by zzusunquan** [comment]
Hi
I try your latest commit ,but a bug has appeared.
Traceback (most recent call last):
 ```
 File "partition/write_Semantic3d.py", line 77, in <module>
    labels_ups = interpolate_labels_batch(data_file, xyz, labels_full, args.ver_batch)
  File "/home/s206/Documents/sunquan/superpoint_graph-ssp-spg/partition/provider.py", line 620, in interpolate_labels_batch
    print("read lines %d to %d" % (i_rows, i_rows + ver_batch))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by zzusunquan** [comment]
> Hi,
> 
> It is indeed a bug, it should be fixed now. Let me know if the latest commit fixes your issue.
I  comment line 620,in interpolate_labels_batch  print("read lines %d to %d" % (i_rows, i_rows + ver_batch)) to solv the typeError .so that the code can tun .
But the labels less one line not solved .
![image](https://user-images.githubusercontent.com/48703273/69391168-e4f12900-0d0c-11ea-8556-620d65ded01d.png)
![image](https://user-images.githubusercontent.com/48703273/69391181-f20e1800-0d0c-11ea-9ed2-237b928ad677.png)
If I had a problem with partitioning or some other step ?

**Comment by zzusunquan** [comment]
Hi！
I am sorry to bother you again, I tried your latest submission, and the result is still one less line. I want to ask if everything is normal after you modify the code.

**Comment by loicland** [comment]
Hi,

Sorry for delay I am currently travelling and can't check the code right now. I will get to it tomorrow afternoon.

In the meantime if you want to look for yourself, the bug is certainly due to my replacing numpy.genfromtext with panda functions.

**Comment by zzusunquan** [comment]
> 你好
> 
> 抱歉，我目前正在旅行，暂时无法检查代码。我明天下午去。
Thank you very much for your reply, I wish you a pleasant trip, I will try it myself, I will inform you in time, but my code level is very limited, I will try hard.

**Comment by zzusunquan** [comment]
> 你好
> 
> 抱歉，我目前正在旅行，暂时无法检查代码。我明天下午去。
> 
> 同时，如果您想寻找自己，则该错误肯定是由于我将numpy.genfromtext替换为panda函数。
![image](https://user-images.githubusercontent.com/48703273/69537790-ce242e00-0fbb-11ea-8595-f777916bcacf.png)
Thank you for your help, I have successfully reproduced the results, I wish you a pleasant journey.

**Comment by loicland** [comment]
Great, could you post your fix please?

**Comment by zzusunquan** [comment]
Following the ideas you provided, make the following changes：
partition/write_Semantic3d.py   74 lines chang it to 
`    labels_ups = interpolate_labels_batch(data_file, xyz, labels_full, args.ver_batch) + 1
`
partition/provider.py        607 to 650 lines
![image](https://user-images.githubusercontent.com/48703273/69542252-04ff4180-0fc6-11ea-8dee-35b251180f62.png)
